version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    networks:
      - redmine-network
    environment:
      MYSQL_ROOT_PASSWORD: mariarootpass
      MYSQL_DATABASE: redmine-db
      MYSQL_USER: redmineuser
      MYSQL_PASSWORD: userpass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    mem_limit: 512m
    volumes:
      - ./data/db:/var/lib/mysql

  redmine:
    image: redmine:6.0
    container_name: redmine-container
    restart: always
    depends_on:
      - mysql
    networks:
      - redmine-network
    environment:
      REDMINE_DB_MYSQL: mysql-container
      REDMINE_DB_DATABASE: redmine-db
      REDMINE_DB_USERNAME: redmineuser
      REDMINE_DB_PASSWORD: userpass
    ports:
      - "8080:3000"
    volumes:
      - ./data/files:/usr/src/redmine/files
      - ./data/plugins:/usr/src/redmine/plugins
      - ./data/themes:/usr/src/redmine/public/themes

networks:
  redmine-network:

volumes:
  mysql_data:
  redmine_data:
